### ISSUE TITLE
Error: Not working after installation

### ISSUE THREAD

**Issue by PardesiCat** [felipealfonsog/TermPDFViewer#51] opened 2023-08-30 11:07 UTC
Hei  am getting error using term-pdf 

downloaded from aur using pikaur

even tried with makepkg -s    none work same error

## Error details

![term-pdf](https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/0d29a716-bb33-49cc-8dcc-130312968157)

**Comment by felipealfonsog** [comment] 2023-08-31 06:28
Hello there! It's fantastic to see you giving term-pdf a try! 😄 What sort of issue are you encountering during the installation process? Could you kindly share the error message you're receiving? My suggestion would be to give `yay` a shot. I've personally tested it on both Arch Linux and Mac on two different machines, and it's worked seamlessly for me. Remember, there's also a bash installer available! Make sure to take a look at the readme for guidance. If you could give it a try and let me know if any errors persist, that would be wonderful. Feel free to send over any errors you encounter so I can help analyze them. Wishing you all the best! 🌟

**Comment by PardesiCat** [comment] 2023-08-31 07:42
hei during install i dint see any problem   
am putting the install log

https://lenp.pardesicat.xyz/hO1MBAyq

even using yay  same   no  error during install  only while running

**Comment by PardesiCat** [comment] 2023-08-31 07:58
and 2nd  i also directly tried to run the  binary file 

its also same error as you can see

![bin](https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/5f0f6a00-7ea0-4ad7-90be-622a3cf77046)

**Comment by felipealfonsog** [comment] 2023-09-01 03:08
Greetings!
Observing a smooth installation process, it appears that the program has been integrated seamlessly into your system. However, to proceed with a thorough analysis, I require additional insights into your system's configuration. I recommend delving into potential underlying issues on your end, after which I would be delighted to offer a comprehensive analysis.

Please keep in mind that an alternative route is available through the utilization of a bash installer. For your convenience, the following link provides access to detailed instructions: [TermPDFViewer Bash Installer](https://github.com/felipealfonsog/TermPDFViewer#install-using-a-bash-script)

Your enthusiasm for resolving this matter is greatly appreciated!
Best regards!

**Comment by PardesiCat** [comment] 2023-09-01 07:36
![ttt](https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/e61f7998-3d12-4750-a512-67d434e87f1f)

nah sir its same error


i have 1 question regarding this  
is it possible to make a install script where  each users will compile the bin from source code   without installing precompilled bin?

**Comment by felipealfonsog** [comment] 2023-09-01 17:23
It appears that there might be a configuration issue within your system. While the installation process itself seems to proceed smoothly, my observation, particularly in the last screenshot, suggests a potential concern with 'pip' in your Arch Linux environment. It's crucial to ensure that 'pip' is configured correctly to facilitate the seamless installation of Python packages, particularly those essential to the program's dependencies.

Therefore, I recommend revisiting your 'pip' configuration to ensure its proper setup. Once this crucial step is accomplished, you can confidently proceed with the program's installation, either by utilizing the provided bash installer or through the 'yay' package manager. It's important to note that if the 'pip' configuration isn't addressed correctly, the manner in which the system installs the program may become inconsequential.

Your proactive approach to resolving this matter is highly commendable. 👍🚀

**Comment by PardesiCat** [comment] 2023-09-01 19:02
Hei nah   my system is oke  with up2date python and its depends


here msg saying becoz term pdf   installer.sh  installing some python depends  as pip install 

where in arch linux  for whole system we use  with   python-package name 

example 

![arch](https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/ed45c26c-bad1-44c6-9562-7a1536fcc6c4)

**Comment by felipealfonsog** [comment] 2023-09-01 21:28
I appreciate your insight and clarification. It appears that the error you've encountered stems from the presence of the "-EXTERNALLY-MANAGED-" option for Python, which should be properly configured or omitted to enable the smooth installation of Python packages via pip.
This is the error in one of your screenshots:
```
$ pip install .
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.

    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.

    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.
```
Addressing this configuration issue is indeed crucial, and it's quite likely the root cause of the problem you've encountered while attempting to run the program. Since there don't appear to be any other evident errors, resolving this Python configuration issue should pave the way for the program to function optimally on your system.

Your diligence in identifying and addressing this matter is greatly appreciated! If you have any further questions or require assistance with the configuration, please don't hesitate to reach out. Cheers, and thank you for your cooperation!

**Comment by PardesiCat** [comment] 2023-09-02 03:35
> Addressing this configuration issue is indeed crucial, and it's quite likely the root cause of the problem you've encountered while attempting to run the program. Since there don't appear to be any other evident errors, resolving this Python configuration issue should pave the way for the program to function optimally on your system.



Hi, this is not a crusial problem; it's showing because the install.sh script is directly running **pip install** (even without venv, aka virtual env).

Because today's major Linux distros don't let you install pip directly, coz it  break the system and make conflict with linux other packages.

That is why Python-Pip packages are individually packaged by the Linux distributors.

Here, this article explains it. https://peps.python.org/pep-0668/


2.nd  if this is causing problem then   when am installing using  yay , pikaur  , makepkg -s    from aur   this error not showing 


3. i think  in my pov   i should  try to compile the project in my system and send the log too you  so you can check in dept 
( or maybe  compile the project in particular machine should fix the problem )

**Comment by felipealfonsog** [comment] 2023-09-02 07:41
Hey 👋 
I extend my gratitude for your valuable commentary, which has been instrumental in fostering a nuanced discourse regarding the utilization of externally managed pip in the context of Python. I wish to acknowledge the acumen embedded in your insights.

It is imperative to underscore that the issue at hand exhibits a degree of variability contingent upon the unique configurations and system architectures embraced by individual users. Indeed, the exposition within PEP 0668 corroborates that Linux distributions, in light of potential conflicts with system-level packages, tend to autonomously oversee Python-Pip packages. However, it is incumbent upon us to recognize that this state of affairs may potentially assume a critical dimension under specific circumstances, drawing from my contemporary cognizance substantiated by empirical data and past experiential insights.

This prompts the consideration that the observed phenomenon could be construed as either an anomaly or a configuration requiring diligent scrutiny. Personally, I have habitually adhered to the practice of not encountering analogous anomalies or system corruption when resorting to this methodology. I adopt this approach primarily to ensure compatibility in the realm of Python package installations, extending its application to macOS.

It is paramount to acknowledge that, while the prevailing convention advocates the segregation of environments, it is not an unassailable dogma. As articulated in the aforementioned article, the desirability of maintaining segregated environments is not an absolute proposition. This suggests that, contingent upon the intricacies of one’s configuration and system, the externalization of pip may not necessarily precipitate issues. My contention emanates from the perspective that, as an engineer, there exist certain scenarios where the adoption of this practice may not be considered ideal. Furthermore, grounded in my extensive professional experience, I posit the existence of packages unattainable outside the purview of pip, thereby buttressing my aforementioned recommendation.

Consonant with the canonical Python documentation, the principal counsel avers the inadvisability of externalizing pip, especially in the realm of Linux. This counsel arises from the rationale that the internal management of pip obviates the potential for conflicts with system-level packages, thus underpinning the stability of the Python ecosystem.

Furthermore, a RealPython publication underscores the pertinence of this discussion by highlighting that the externalization of pip can yield compatibility challenges and intricacies in package management, given the proclivity of certain packages and tools to rely on internal pip management for seamless operation.

I proffer a supplementary observation pertaining to my personal engagement with another software platform wherein machine learning libraries and their dependencies are indispensable. Regrettably, these libraries remain solely accessible within the confines of the pip environment. This facet has assumed paramount importance, given my multifaceted development endeavors spanning diverse platforms, encompassing Linux and macOS alike. Consequently, the capacity to leverage these libraries has become instrumental in ensuring the efficacy and compatibility of my developmental pursuits.

In denouement, I proffer the suggestion that you endeavor to compile my project within your system’s milieu and furnish me with error logs. Such a meticulous examination could potentially furnish insights into system-specific issues. It is imperative to acknowledge the inherent variability in configurations and challenges across disparate systems. Therefore, adherence to the guidance provided by respective programs remains indispensable to engender a consistent and harmonious user experience.

In closing, I trust that this response elucidates your circumstances and contributes to the cultivation of a judicious and effective resolution.

**Comment by felipealfonsog** [comment] 2023-09-05 04:45
> > Addressing this configuration issue is indeed crucial, and it's quite likely the root cause of the problem you've encountered while attempting to run the program. Since there don't appear to be any other evident errors, resolving this Python configuration issue should pave the way for the program to function optimally on your system.
> 
> Hi, this is not a crusial problem; it's showing because the install.sh script is directly running **pip install** (even without venv, aka virtual env).
> 
> Because today's major Linux distros don't let you install pip directly, coz it break the system and make conflict with linux other packages.
> 
> That is why Python-Pip packages are individually packaged by the Linux distributors.
> 
> Here, this article explains it. https://peps.python.org/pep-0668/
> 
> 2.nd if this is causing problem then when am installing using yay , pikaur , makepkg -s from aur this error not showing
> 
> 3. i think  in my pov   i should  try to compile the project in my system and send the log too you  so you can check in dept
>    ( or maybe  compile the project in particular machine should fix the problem )

Hey there, Have you been successful in achieving the desired functionality, or have you encountered any error log messages?, Cheers!.

**Comment by PardesiCat** [comment] 2023-09-06 08:01
hei  im new in this  field  idk how to compile the project

but looks like   python file in src folder working fine



![py](https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/b8468327-4d7a-47d8-bfe7-2c00525d3f08)

**Comment by felipealfonsog** [comment] 2023-09-06 08:49
Thank you for the feedback! I'm considering making some improvements to enhance the installation process on-the-fly. Additionally, I'm exploring options to streamline the compilation process. I'm even open to changing the programming language if necessary. By the way, would you be interested in contributing, perhaps through translation? Cheers! 🤘👍🚀

**Comment by PardesiCat** [comment] 2023-09-06 09:05
Yess i  will try my best to contribute in project

**Comment by felipealfonsog** [comment] 2023-09-06 09:14
Your contribution to documentation would also be greatly appreciated. Are you interested in participating in Term-Notes as well? 🤘

**Comment by PardesiCat** [comment] 2023-09-06 14:14
yess sir

**Closed** 2023-09-12 02:22 UTC
